name: zkPass-airdrop-indexer
description: zkPass airdrop indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: Schema
    abi_file_path: ./abis/schema-abi.json
    handler: ./src/SchemaEventHandlers.js
    events:
      - event: SchemaRegistered(bytes32 indexed uid, address registerer, string schemaURI, string schemaData, bool revocable)
      - event: SchemaDataRevised(bytes32 indexed uid, string schemaData)
      - event: SchemaRevoked(bytes32 indexed uid)
  - name: Zas
    abi_file_path: ./abis/zas-abi.json
    handler: ./src/ZasEventHandlers.js
    events:
      - event: Attested(address indexed recipient, address indexed notary, address allocator, bytes32 uid, bytes32 indexed schema, bytes32 nullifier)
      - event: Revoked(address indexed recipient, address indexed revoker, bytes32 uid, bytes32 indexed schema, bytes32 nullifier)
networks:
  # - id: 1 # ETH
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  - id: 56 # BSC
    start_block: 38290127
    contracts:
      - name: Schema
        address: "0xDB9323A6ADAaecA7d778E33190154C96E8913f0E"
      - name: Zas
        address: "0x7D3F2EE6800da3D1ad1ed5d32349a39f12342886"
  - id: 59144 # Linea
    start_block: 4123427
    contracts:
      - name: Schema
        address: "0x922fe9530689D1AA0347daA0589b2F1961D57788"
      - name: Zas
        address: "0x4d0eBafdA4020A9192808a4792c6AD0A2c928ADE"
  - id: 534352 # Scroll
    start_block: 5238940
    contracts:
      - name: Schema
        address: "0xE0748C3537Aa4110BC356e96Fa368E18dB7eD782"
      - name: Zas
        address: "0xb1fEFBe5E30EC4e26c42d7137A0e40C38E76E241"
  - id: 42161 # Arbitrum One
    start_block: 206121803 
    contracts:
      - name: Schema
        address: "0x6bDeE5F216cfB9427D7309432022AB56c64093E9"
      - name: Zas
        address: "0x574eafbd829AB00068958e0fAC5468B644FBFa83"
  - id: 324 # zkSync Era
    start_block: 32712932
    contracts:
      - name: Schema
        address: "0x49691a44Dee3A0411C5160E4cfd8f2e52Afb1D5D"
      - name: Zas
        address: "0x7Ed552AbE9e2ba44cDa257D4B510a18480c161D3"
  - id: 10 # Optimism
    start_block: 119435096
    contracts:
      - name: Schema
        address: "0xEaCbd088101759f73724dE578AadF36CEcdc3B5e"
      - name: Zas
        address: "0x3b30D7C4e5aa3d7dA11431aF23e8D1F7D25bB0B8"
  # - id: 137 # Polygon
  #   start_block: 0
  #   contracts:
  #     - name: Schema
  #       address: ""
  #     - name: Zas
  #       address: ""
  - id: 8453 # Base
    start_block: 13840270
    contracts:
      - name: Schema
        address: "0xEaCbd088101759f73724dE578AadF36CEcdc3B5e"
      - name: Zas
        address: "0x3b30D7C4e5aa3d7dA11431aF23e8D1F7D25bB0B8"